hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/catalog-backend
  tag: development-326a48d
networkPolicy:
  allowedServices:
    - user-backend
    - identity-backend
    - order-backend
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1300Mi
  requests:
    cpu: 35m
    memory: 845Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: development
database:
  hikariMaxPool: 30
  hikariMinIdle: 10
